@baseUrl = http://localhost:8080

### Sign in and get authentication token
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Save token to global variable for further requests
> {% client.global.set("token", response.body.token); %}

### Get all routes
GET {{baseUrl}}/api/routes

### Get all users
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}

### Get all carriage types
GET {{baseUrl}}/api/carriages

### Get all stations
GET {{baseUrl}}/api/station

### Get orders for current user
GET {{baseUrl}}/api/order
Authorization: Bearer {{token}}

### Get all orders
GET {{baseUrl}}/api/order?all=true
Authorization: Bearer {{token}}

### Get information about route and its rides
GET {{baseUrl}}/api/routes/1
Authorization: Bearer {{token}}

### Get detailed information about ride
GET {{baseUrl}}/api/search/1

### Search for available rides
GET {{baseUrl}}/api/search?
    fromLatitude=54.5&
    fromLongitude=18.5&
    toLatitude=54.351&
    toLongitude=18.7&
    time=1762866687

### Create new route
POST {{baseUrl}}/api/route
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "path": [1, 2, 3],
  "carriages": ["1st class", "2nd class", "3rd class", "3rd class", "2nd class", "1st class"]
}

### Create new carriage type
POST {{baseUrl}}/api/carriage
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "4th class",
  "rows": 100,
  "leftSeats": 3,
  "rightSeats": 6
}

### Create new station
POST {{baseUrl}}/api/station
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "city": "Warszawa",
  "latitude": 52.22977,
  "longitude": 21.01178,
  "relations": [1, 2, 3]
}

### Create new user
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
  "email": "test_user2@gmail.com",
  "password": "test_password"
}

### Create new ride for the route
POST {{baseUrl}}/api/route/1/ride
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "segments": [
    {
      "time": [
        "2024-11-15T22:15:00",
        "2024-11-15T22:30:00"
      ],
      "price": {
        "1st class": 100,
        "2nd class": 50,
        "3rd class": 25
      }
    },
    {
      "time": [
        "2024-11-15T22:30:00",
        "2024-11-15T22:45:00"
      ],
      "price": {
        "1st class": 100,
        "2nd class": 50,
        "3rd class": 25
      }
    }
  ]
}

### Create new order
POST {{baseUrl}}/api/order
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "rideId": 1,
  "seatId": 8,
  "stationStart": 1,
  "stationEnd": 3
}

### Delete order
DELETE {{baseUrl}}/api/order/4
Authorization: Bearer {{token}}

### Delete carriage type
DELETE {{baseUrl}}/api/carriage/21537160-6014-40ed-b0f6-966e90238e1e
Authorization: Bearer {{token}}

### Delete station
DELETE {{baseUrl}}/api/station/4
Authorization: Bearer {{token}}

### Delete route
DELETE {{baseUrl}}/api/route/4
Authorization: Bearer {{token}}

### Delete ride
DELETE {{baseUrl}}/api/route/1/ride/4
Authorization: Bearer {{token}}

### Update route
PUT {{baseUrl}}/api/route/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "path": [1, 3],
  "carriages": ["1st class", "2nd class", "1st class"]
}

### Update carriage type
PUT {{baseUrl}}/api/carriage/{carriageId}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "3rd class",
  "rows": 40,
  "leftSeats": 3,
  "rightSeats": 3
}

### Update ride
PUT {{baseUrl}}/api/route/1/ride/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "segments": [
    {
      "time": [
        "2024-11-15T20:15:00",
        "2024-11-15T21:30:00"
      ],
      "price": {
        "1st class": 1000,
        "2nd class": 500,
        "3rd class": 250
      }
    },
    {
      "time": [
        "2024-11-15T22:30:00",
        "2024-11-15T23:45:00"
      ],
      "price": {
        "1st class": 100,
        "2nd class": 50,
        "3rd class": 25
      }
    }
  ]
}

### Update user profile
PUT {{baseUrl}}/api/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "new@email.com",
  "name": "John Doe"
}

### Update user password
PUT {{baseUrl}}/api/profile/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "new-password123"
}

### Get user profile information
GET {{baseUrl}}/api/profile
Authorization: Bearer {{token}}
