@baseUrl = http://localhost:8083

### Get all routes
GET {{baseUrl}}/api/route

> {% client.global.set("token", ""); %}

### Get all carriage types
GET {{baseUrl}}/api/carriage

### Get all stations
GET {{baseUrl}}/api/station

### Get detailed information about ride
GET {{baseUrl}}/api/search/1

### Search for available rides
GET {{baseUrl}}/api/search?
    fromLatitude=54.5&
    fromLongitude=18.5&
    toLatitude=54.351&
    toLongitude=18.7&
    time=1762866687

### Create new user
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "Password123."
}
